// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/avdoseferovic/paper/pkg/core"
	entity "github.com/avdoseferovic/paper/pkg/core/entity"

	mock "github.com/avdoseferovic/paper/internal/mocktest"

	node "github.com/avdoseferovic/paper/pkg/tree/node"
)

// Paper is an autogenerated mock type for the Paper type
type Paper struct {
	mock.Mock
}

type Paper_Expecter struct {
	mock *mock.Mock
}

func (_m *Paper) EXPECT() *Paper_Expecter {
	return &Paper_Expecter{mock: &_m.Mock}
}

// AddAutoRow provides a mock function with given fields: cols
func (_m *Paper) AddAutoRow(cols ...core.Col) core.Row {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddAutoRow")
	}

	var r0 core.Row
	if rf, ok := ret.Get(0).(func(...core.Col) core.Row); ok {
		r0 = rf(cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Row)
		}
	}

	return r0
}

// Paper_AddAutoRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAutoRow'
type Paper_AddAutoRow_Call struct {
	*mock.Call
}

// AddAutoRow is a helper method to define mock.On call
//   - cols ...core.Col
func (_e *Paper_Expecter) AddAutoRow(cols ...interface{}) *Paper_AddAutoRow_Call {
	return &Paper_AddAutoRow_Call{Call: _e.mock.On("AddAutoRow",
		append([]interface{}{}, cols...)...)}
}

func (_c *Paper_AddAutoRow_Call) Run(run func(cols ...core.Col)) *Paper_AddAutoRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Col, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Col)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Paper_AddAutoRow_Call) Return(_a0 core.Row) *Paper_AddAutoRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_AddAutoRow_Call) RunAndReturn(run func(...core.Col) core.Row) *Paper_AddAutoRow_Call {
	_c.Call.Return(run)
	return _c
}

// AddHTML provides a mock function with given fields: ctx, htmlStr
func (_m *Paper) AddHTML(ctx context.Context, htmlStr string) error {
	ret := _m.Called(ctx, htmlStr)

	if len(ret) == 0 {
		panic("no return value specified for AddHTML")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, htmlStr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Paper_AddHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHTML'
type Paper_AddHTML_Call struct {
	*mock.Call
}

// AddHTML is a helper method to define mock.On call
//   - ctx context.Context
//   - htmlStr string
func (_e *Paper_Expecter) AddHTML(ctx interface{}, htmlStr interface{}) *Paper_AddHTML_Call {
	return &Paper_AddHTML_Call{Call: _e.mock.On("AddHTML", ctx, htmlStr)}
}

func (_c *Paper_AddHTML_Call) Run(run func(ctx context.Context, htmlStr string)) *Paper_AddHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Paper_AddHTML_Call) Return(_a0 error) *Paper_AddHTML_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_AddHTML_Call) RunAndReturn(run func(context.Context, string) error) *Paper_AddHTML_Call {
	_c.Call.Return(run)
	return _c
}

// AddPages provides a mock function with given fields: pages
func (_m *Paper) AddPages(pages ...core.Page) {
	_va := make([]interface{}, len(pages))
	for _i := range pages {
		_va[_i] = pages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Paper_AddPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPages'
type Paper_AddPages_Call struct {
	*mock.Call
}

// AddPages is a helper method to define mock.On call
//   - pages ...core.Page
func (_e *Paper_Expecter) AddPages(pages ...interface{}) *Paper_AddPages_Call {
	return &Paper_AddPages_Call{Call: _e.mock.On("AddPages",
		append([]interface{}{}, pages...)...)}
}

func (_c *Paper_AddPages_Call) Run(run func(pages ...core.Page)) *Paper_AddPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Page, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Page)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Paper_AddPages_Call) Return() *Paper_AddPages_Call {
	_c.Call.Return()
	return _c
}

func (_c *Paper_AddPages_Call) RunAndReturn(run func(...core.Page)) *Paper_AddPages_Call {
	_c.Run(run)
	return _c
}

// AddRow provides a mock function with given fields: rowHeight, cols
func (_m *Paper) AddRow(rowHeight float64, cols ...core.Col) core.Row {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, rowHeight)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddRow")
	}

	var r0 core.Row
	if rf, ok := ret.Get(0).(func(float64, ...core.Col) core.Row); ok {
		r0 = rf(rowHeight, cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Row)
		}
	}

	return r0
}

// Paper_AddRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRow'
type Paper_AddRow_Call struct {
	*mock.Call
}

// AddRow is a helper method to define mock.On call
//   - rowHeight float64
//   - cols ...core.Col
func (_e *Paper_Expecter) AddRow(rowHeight interface{}, cols ...interface{}) *Paper_AddRow_Call {
	return &Paper_AddRow_Call{Call: _e.mock.On("AddRow",
		append([]interface{}{rowHeight}, cols...)...)}
}

func (_c *Paper_AddRow_Call) Run(run func(rowHeight float64, cols ...core.Col)) *Paper_AddRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Col, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(core.Col)
			}
		}
		run(args[0].(float64), variadicArgs...)
	})
	return _c
}

func (_c *Paper_AddRow_Call) Return(_a0 core.Row) *Paper_AddRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_AddRow_Call) RunAndReturn(run func(float64, ...core.Col) core.Row) *Paper_AddRow_Call {
	_c.Call.Return(run)
	return _c
}

// AddRows provides a mock function with given fields: rows
func (_m *Paper) AddRows(rows ...core.Row) {
	_va := make([]interface{}, len(rows))
	for _i := range rows {
		_va[_i] = rows[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Paper_AddRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRows'
type Paper_AddRows_Call struct {
	*mock.Call
}

// AddRows is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Paper_Expecter) AddRows(rows ...interface{}) *Paper_AddRows_Call {
	return &Paper_AddRows_Call{Call: _e.mock.On("AddRows",
		append([]interface{}{}, rows...)...)}
}

func (_c *Paper_AddRows_Call) Run(run func(rows ...core.Row)) *Paper_AddRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Row, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Row)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Paper_AddRows_Call) Return() *Paper_AddRows_Call {
	_c.Call.Return()
	return _c
}

func (_c *Paper_AddRows_Call) RunAndReturn(run func(...core.Row)) *Paper_AddRows_Call {
	_c.Run(run)
	return _c
}

// FitInCurrentPage provides a mock function with given fields: heightNewLine
func (_m *Paper) FitInCurrentPage(heightNewLine float64) bool {
	ret := _m.Called(heightNewLine)

	if len(ret) == 0 {
		panic("no return value specified for FitInCurrentPage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64) bool); ok {
		r0 = rf(heightNewLine)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Paper_FitInCurrentPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FitInCurrentPage'
type Paper_FitInCurrentPage_Call struct {
	*mock.Call
}

// FitInCurrentPage is a helper method to define mock.On call
//   - heightNewLine float64
func (_e *Paper_Expecter) FitInCurrentPage(heightNewLine interface{}) *Paper_FitInCurrentPage_Call {
	return &Paper_FitInCurrentPage_Call{Call: _e.mock.On("FitInCurrentPage", heightNewLine)}
}

func (_c *Paper_FitInCurrentPage_Call) Run(run func(heightNewLine float64)) *Paper_FitInCurrentPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *Paper_FitInCurrentPage_Call) Return(_a0 bool) *Paper_FitInCurrentPage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_FitInCurrentPage_Call) RunAndReturn(run func(float64) bool) *Paper_FitInCurrentPage_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with given fields: ctx
func (_m *Paper) Generate(ctx context.Context) (*core.Pdf, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 *core.Pdf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*core.Pdf, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *core.Pdf); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Pdf)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paper_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Paper_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Paper_Expecter) Generate(ctx interface{}) *Paper_Generate_Call {
	return &Paper_Generate_Call{Call: _e.mock.On("Generate", ctx)}
}

func (_c *Paper_Generate_Call) Run(run func(ctx context.Context)) *Paper_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Paper_Generate_Call) Return(_a0 *core.Pdf, _a1 error) *Paper_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Paper_Generate_Call) RunAndReturn(run func(context.Context) (*core.Pdf, error)) *Paper_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentConfig provides a mock function with no fields
func (_m *Paper) GetCurrentConfig() *entity.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentConfig")
	}

	var r0 *entity.Config
	if rf, ok := ret.Get(0).(func() *entity.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Config)
		}
	}

	return r0
}

// Paper_GetCurrentConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentConfig'
type Paper_GetCurrentConfig_Call struct {
	*mock.Call
}

// GetCurrentConfig is a helper method to define mock.On call
func (_e *Paper_Expecter) GetCurrentConfig() *Paper_GetCurrentConfig_Call {
	return &Paper_GetCurrentConfig_Call{Call: _e.mock.On("GetCurrentConfig")}
}

func (_c *Paper_GetCurrentConfig_Call) Run(run func()) *Paper_GetCurrentConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Paper_GetCurrentConfig_Call) Return(_a0 *entity.Config) *Paper_GetCurrentConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_GetCurrentConfig_Call) RunAndReturn(run func() *entity.Config) *Paper_GetCurrentConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructure provides a mock function with no fields
func (_m *Paper) GetStructure() *node.Node[core.Structure] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStructure")
	}

	var r0 *node.Node[core.Structure]
	if rf, ok := ret.Get(0).(func() *node.Node[core.Structure]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node[core.Structure])
		}
	}

	return r0
}

// Paper_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Paper_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Paper_Expecter) GetStructure() *Paper_GetStructure_Call {
	return &Paper_GetStructure_Call{Call: _e.mock.On("GetStructure")}
}

func (_c *Paper_GetStructure_Call) Run(run func()) *Paper_GetStructure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Paper_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Paper_GetStructure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Paper_GetStructure_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFooter provides a mock function with given fields: rows
func (_m *Paper) RegisterFooter(rows ...core.Row) error {
	_va := make([]interface{}, len(rows))
	for _i := range rows {
		_va[_i] = rows[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFooter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...core.Row) error); ok {
		r0 = rf(rows...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Paper_RegisterFooter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFooter'
type Paper_RegisterFooter_Call struct {
	*mock.Call
}

// RegisterFooter is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Paper_Expecter) RegisterFooter(rows ...interface{}) *Paper_RegisterFooter_Call {
	return &Paper_RegisterFooter_Call{Call: _e.mock.On("RegisterFooter",
		append([]interface{}{}, rows...)...)}
}

func (_c *Paper_RegisterFooter_Call) Run(run func(rows ...core.Row)) *Paper_RegisterFooter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Row, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Row)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Paper_RegisterFooter_Call) Return(_a0 error) *Paper_RegisterFooter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_RegisterFooter_Call) RunAndReturn(run func(...core.Row) error) *Paper_RegisterFooter_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHeader provides a mock function with given fields: rows
func (_m *Paper) RegisterHeader(rows ...core.Row) error {
	_va := make([]interface{}, len(rows))
	for _i := range rows {
		_va[_i] = rows[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...core.Row) error); ok {
		r0 = rf(rows...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Paper_RegisterHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHeader'
type Paper_RegisterHeader_Call struct {
	*mock.Call
}

// RegisterHeader is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Paper_Expecter) RegisterHeader(rows ...interface{}) *Paper_RegisterHeader_Call {
	return &Paper_RegisterHeader_Call{Call: _e.mock.On("RegisterHeader",
		append([]interface{}{}, rows...)...)}
}

func (_c *Paper_RegisterHeader_Call) Run(run func(rows ...core.Row)) *Paper_RegisterHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Row, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Row)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Paper_RegisterHeader_Call) Return(_a0 error) *Paper_RegisterHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Paper_RegisterHeader_Call) RunAndReturn(run func(...core.Row) error) *Paper_RegisterHeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaper creates a new instance of Paper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaper(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Paper {
	mock := &Paper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
