// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/avdoseferovic/paper/internal/mocktest"
	entity "github.com/avdoseferovic/paper/pkg/core/entity"

	props "github.com/avdoseferovic/paper/pkg/props"
)

// RichTextProvider is an autogenerated mock type for the RichTextProvider type
type RichTextProvider struct {
	mock.Mock
}

type RichTextProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RichTextProvider) EXPECT() *RichTextProvider_Expecter {
	return &RichTextProvider_Expecter{mock: &_m.Mock}
}

// AddRichText provides a mock function with given fields: runs, cell, prop
func (_m *RichTextProvider) AddRichText(runs []props.RichRun, cell *entity.Cell, prop *props.RichText) {
	_m.Called(runs, cell, prop)
}

// RichTextProvider_AddRichText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRichText'
type RichTextProvider_AddRichText_Call struct {
	*mock.Call
}

// AddRichText is a helper method to define mock.On call
//   - runs []props.RichRun
//   - cell *entity.Cell
//   - prop *props.RichText
func (_e *RichTextProvider_Expecter) AddRichText(runs interface{}, cell interface{}, prop interface{}) *RichTextProvider_AddRichText_Call {
	return &RichTextProvider_AddRichText_Call{Call: _e.mock.On("AddRichText", runs, cell, prop)}
}

func (_c *RichTextProvider_AddRichText_Call) Run(run func(runs []props.RichRun, cell *entity.Cell, prop *props.RichText)) *RichTextProvider_AddRichText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]props.RichRun), args[1].(*entity.Cell), args[2].(*props.RichText))
	})
	return _c
}

func (_c *RichTextProvider_AddRichText_Call) Return() *RichTextProvider_AddRichText_Call {
	_c.Call.Return()
	return _c
}

func (_c *RichTextProvider_AddRichText_Call) RunAndReturn(run func([]props.RichRun, *entity.Cell, *props.RichText)) *RichTextProvider_AddRichText_Call {
	_c.Run(run)
	return _c
}

// AddTextAt provides a mock function with given fields: x, y, text, prop
func (_m *RichTextProvider) AddTextAt(x float64, y float64, text string, prop *props.Text) {
	_m.Called(x, y, text, prop)
}

// RichTextProvider_AddTextAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTextAt'
type RichTextProvider_AddTextAt_Call struct {
	*mock.Call
}

// AddTextAt is a helper method to define mock.On call
//   - x float64
//   - y float64
//   - text string
//   - prop *props.Text
func (_e *RichTextProvider_Expecter) AddTextAt(x interface{}, y interface{}, text interface{}, prop interface{}) *RichTextProvider_AddTextAt_Call {
	return &RichTextProvider_AddTextAt_Call{Call: _e.mock.On("AddTextAt", x, y, text, prop)}
}

func (_c *RichTextProvider_AddTextAt_Call) Run(run func(x float64, y float64, text string, prop *props.Text)) *RichTextProvider_AddTextAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(float64), args[2].(string), args[3].(*props.Text))
	})
	return _c
}

func (_c *RichTextProvider_AddTextAt_Call) Return() *RichTextProvider_AddTextAt_Call {
	_c.Call.Return()
	return _c
}

func (_c *RichTextProvider_AddTextAt_Call) RunAndReturn(run func(float64, float64, string, *props.Text)) *RichTextProvider_AddTextAt_Call {
	_c.Run(run)
	return _c
}

// MeasureString provides a mock function with given fields: text, prop
func (_m *RichTextProvider) MeasureString(text string, prop *props.Text) float64 {
	ret := _m.Called(text, prop)

	if len(ret) == 0 {
		panic("no return value specified for MeasureString")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, *props.Text) float64); ok {
		r0 = rf(text, prop)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// RichTextProvider_MeasureString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureString'
type RichTextProvider_MeasureString_Call struct {
	*mock.Call
}

// MeasureString is a helper method to define mock.On call
//   - text string
//   - prop *props.Text
func (_e *RichTextProvider_Expecter) MeasureString(text interface{}, prop interface{}) *RichTextProvider_MeasureString_Call {
	return &RichTextProvider_MeasureString_Call{Call: _e.mock.On("MeasureString", text, prop)}
}

func (_c *RichTextProvider_MeasureString_Call) Run(run func(text string, prop *props.Text)) *RichTextProvider_MeasureString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*props.Text))
	})
	return _c
}

func (_c *RichTextProvider_MeasureString_Call) Return(_a0 float64) *RichTextProvider_MeasureString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RichTextProvider_MeasureString_Call) RunAndReturn(run func(string, *props.Text) float64) *RichTextProvider_MeasureString_Call {
	_c.Call.Return(run)
	return _c
}

// NewRichTextProvider creates a new instance of RichTextProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRichTextProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *RichTextProvider {
	mock := &RichTextProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
