package pdf

import (
	"bytes"
	"crypto/sha256"
	"encoding/gob"
	"fmt"
)

// ImageInfoType contains size, color and other information about an image.
// Changes to this structure should be reflected in its GobEncode and GobDecode
// methods.
type ImageInfoType struct {
	data  []byte  // Raw image data
	smask []byte  // Soft Mask, an 8bit per-pixel transparency mask
	n     int     // Image object number
	w     float64 // Width
	h     float64 // Height
	cs    string  // Color space
	pal   []byte  // Image color palette
	bpc   int     // Bits Per Component
	f     string  // Image filter
	dp    string  // DecodeParms
	trns  []int   // Transparency mask
	scale float64 // Document scale factor
	dpi   float64 // Dots-per-inch found from image file (png only)
	i     string  // SHA-1 checksum of the above values.
}

func generateImageID(info *ImageInfoType) (string, error) {
	b, err := info.GobEncode()
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", sha256.Sum256(b)), nil
}

// GobEncode encodes the receiving image to a byte slice.
func (info *ImageInfoType) GobEncode() ([]byte, error) {
	fields := []any{
		info.data, info.smask, info.n, info.w, info.h, info.cs,
		info.pal, info.bpc, info.f, info.dp, info.trns, info.scale, info.dpi,
	}
	w := new(bytes.Buffer)
	encoder := gob.NewEncoder(w)
	for j, field := range fields {
		err := encoder.Encode(field)
		if err != nil {
			return nil, fmt.Errorf("encode image field %d: %w", j, err)
		}
	}
	return w.Bytes(), nil
}

// GobDecode decodes the specified byte buffer (generated by GobEncode) into
// the receiving image.
func (info *ImageInfoType) GobDecode(buf []byte) error {
	fields := []any{
		&info.data, &info.smask, &info.n, &info.w, &info.h,
		&info.cs, &info.pal, &info.bpc, &info.f, &info.dp, &info.trns, &info.scale, &info.dpi,
	}
	r := bytes.NewBuffer(buf)
	decoder := gob.NewDecoder(r)
	for j, field := range fields {
		err := decoder.Decode(field)
		if err != nil {
			return fmt.Errorf("decode image field %d: %w", j, err)
		}
	}

	var err error
	info.i, err = generateImageID(info)
	if err != nil {
		return fmt.Errorf("generate image id: %w", err)
	}
	return nil
}

// Extent returns the width and height of the image in the units of the PDF
// object.
func (info *ImageInfoType) Extent() (float64, float64) {
	return info.Width(), info.Height()
}

// Width returns the width of the image in the units of the PDF object.
func (info *ImageInfoType) Width() float64 {
	return info.w / (info.scale * info.dpi / 72)
}

// Height returns the height of the image in the units of the PDF object.
func (info *ImageInfoType) Height() float64 {
	return info.h / (info.scale * info.dpi / 72)
}

// SetDpi sets the dots per inch for an image. PNG images MAY have their dpi
// set automatically, if the image specifies it. DPI information is not
// currently available automatically for JPG and GIF images, so if it's
// important to you, you can set it here. It defaults to 72 dpi.
func (info *ImageInfoType) SetDpi(dpi float64) {
	info.dpi = dpi
}
