coverage:
  precision: 2
  round: up
  range: "70...100"

ignore:
  - ".idea"
  - "internal/mocks"
  - "internal/fixture"
  - "internal/assert"
  - "internal/require"
  - "internal/mocktest"
  - "internal/goleak"
