// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/avdoseferovic/paper/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	props "github.com/avdoseferovic/paper/pkg/props"
)

// RichTextProvider is an autogenerated mock type for the RichTextProvider type
type RichTextProvider struct {
	mock.Mock
}

type RichTextProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RichTextProvider) EXPECT() *RichTextProvider_Expecter {
	return &RichTextProvider_Expecter{mock: &_m.Mock}
}

// MeasureString provides a mock function with given fields: text, prop
func (_m *RichTextProvider) MeasureString(text string, prop *props.Text) float64 {
	ret := _m.Called(text, prop)
	return ret.Get(0).(float64)
}

// RichTextProvider_MeasureString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureString'
type RichTextProvider_MeasureString_Call struct {
	*mock.Call
}

func (_e *RichTextProvider_Expecter) MeasureString(text interface{}, prop interface{}) *RichTextProvider_MeasureString_Call {
	return &RichTextProvider_MeasureString_Call{Call: _e.mock.On("MeasureString", text, prop)}
}

func (_c *RichTextProvider_MeasureString_Call) Run(run func(text string, prop *props.Text)) *RichTextProvider_MeasureString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*props.Text))
	})
	return _c
}

func (_c *RichTextProvider_MeasureString_Call) Return(_a0 float64) *RichTextProvider_MeasureString_Call {
	_c.Call.Return(_a0)
	return _c
}

// AddTextAt provides a mock function with given fields: x, y, text, prop
func (_m *RichTextProvider) AddTextAt(x, y float64, text string, prop *props.Text) {
	_m.Called(x, y, text, prop)
}

// RichTextProvider_AddTextAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTextAt'
type RichTextProvider_AddTextAt_Call struct {
	*mock.Call
}

func (_e *RichTextProvider_Expecter) AddTextAt(x, y, text, prop interface{}) *RichTextProvider_AddTextAt_Call {
	return &RichTextProvider_AddTextAt_Call{Call: _e.mock.On("AddTextAt", x, y, text, prop)}
}

func (_c *RichTextProvider_AddTextAt_Call) Run(run func(x, y float64, text string, prop *props.Text)) *RichTextProvider_AddTextAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(float64), args[2].(string), args[3].(*props.Text))
	})
	return _c
}

func (_c *RichTextProvider_AddTextAt_Call) Return() *RichTextProvider_AddTextAt_Call {
	_c.Call.Return()
	return _c
}

// AddRichText provides a mock function with given fields: runs, cell, prop
func (_m *RichTextProvider) AddRichText(runs []props.RichRun, cell *entity.Cell, prop *props.RichText) {
	_m.Called(runs, cell, prop)
}

// RichTextProvider_AddRichText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRichText'
type RichTextProvider_AddRichText_Call struct {
	*mock.Call
}

func (_e *RichTextProvider_Expecter) AddRichText(runs, cell, prop interface{}) *RichTextProvider_AddRichText_Call {
	return &RichTextProvider_AddRichText_Call{Call: _e.mock.On("AddRichText", runs, cell, prop)}
}

func (_c *RichTextProvider_AddRichText_Call) Run(run func(runs []props.RichRun, cell *entity.Cell, prop *props.RichText)) *RichTextProvider_AddRichText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]props.RichRun), args[1].(*entity.Cell), args[2].(*props.RichText))
	})
	return _c
}

func (_c *RichTextProvider_AddRichText_Call) Return() *RichTextProvider_AddRichText_Call {
	_c.Call.Return()
	return _c
}

// NewRichTextProvider creates a new instance of RichTextProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRichTextProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RichTextProvider {
	mock := &RichTextProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
