// paper-showcase generates a concise PDF tour of Paper's public authoring APIs.
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/avdoseferovic/paper"
	"github.com/avdoseferovic/paper/pkg/components/checkbox"
	"github.com/avdoseferovic/paper/pkg/components/code"
	"github.com/avdoseferovic/paper/pkg/components/col"
	htmlcomponent "github.com/avdoseferovic/paper/pkg/components/html"
	"github.com/avdoseferovic/paper/pkg/components/image"
	"github.com/avdoseferovic/paper/pkg/components/line"
	"github.com/avdoseferovic/paper/pkg/components/richtext"
	"github.com/avdoseferovic/paper/pkg/components/row"
	"github.com/avdoseferovic/paper/pkg/components/signature"
	"github.com/avdoseferovic/paper/pkg/components/table"
	"github.com/avdoseferovic/paper/pkg/components/text"
	"github.com/avdoseferovic/paper/pkg/config"
	"github.com/avdoseferovic/paper/pkg/consts/align"
	"github.com/avdoseferovic/paper/pkg/consts/border"
	"github.com/avdoseferovic/paper/pkg/consts/extension"
	"github.com/avdoseferovic/paper/pkg/consts/fontfamily"
	"github.com/avdoseferovic/paper/pkg/consts/fontstyle"
	"github.com/avdoseferovic/paper/pkg/consts/linestyle"
	"github.com/avdoseferovic/paper/pkg/core"
	"github.com/avdoseferovic/paper/pkg/html/translate"
	"github.com/avdoseferovic/paper/pkg/props"
)

const (
	defaultOutput = "test/output/paper-showcase.pdf"
	serifFont     = "times"
)

var (
	ink        = rgb(58, 50, 43)
	inkSoft    = rgb(94, 84, 74)
	muted      = rgb(126, 115, 103)
	faint      = rgb(178, 168, 154)
	brand      = ink
	teal       = rgb(190, 79, 54)
	green      = rgb(72, 132, 93)
	amber      = rgb(163, 91, 61)
	red        = rgb(150, 56, 39)
	blue       = rgb(78, 101, 158)
	white      = rgb(255, 255, 255)
	canvas     = rgb(250, 248, 244)
	paperShade = rgb(246, 242, 236)
	codeBg     = rgb(252, 250, 247)
	deepInk    = rgb(41, 35, 30)
	softBlue   = rgb(238, 241, 248)
	softTeal   = rgb(251, 240, 236)
	softGold   = rgb(248, 242, 231)
	softRose   = rgb(249, 235, 231)
	borderC    = rgb(226, 219, 209)
	lineSoftC  = rgb(240, 235, 228)
)

func main() {
	out := defaultOutput
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	if err := generateShowcase(out); err != nil {
		log.Fatal(err)
	}
	info, _ := os.Stat(out)
	fmt.Printf("Wrote %s (%d bytes)\n", out, info.Size())
}

func generateShowcase(out string) error {
	doc, err := buildShowcaseDocument()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := doc.Save(out); err != nil {
		return fmt.Errorf("save showcase: %w", err)
	}
	return nil
}

func buildShowcaseDocument() (core.Document, error) {
	m, err := buildShowcasePaper()
	if err != nil {
		return nil, err
	}
	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate showcase: %w", err)
	}
	return doc, nil
}

func buildShowcasePaper() (core.Paper, error) {
	cfg := config.NewBuilder().
		WithLeftMargin(15).
		WithRightMargin(15).
		WithTopMargin(12).
		WithBottomMargin(13).
		WithPageNumber(props.PageNumber{
			Pattern: "Page {current} of {total}",
			Place:   props.RightBottom,
			Family:  fontfamily.Helvetica,
			Size:    7,
			Color:   muted,
		}).
		WithTitle("Paper Showcase", false).
		WithSubject("Component, grid, and HTML examples for Paper", false).
		WithCreator("cmd/paper-showcase", false).
		WithCreationDate(time.Date(2026, time.June, 8, 0, 0, 0, 0, time.UTC)).
		Build()

	m := paper.New(cfg)
	if err := m.RegisterHeader(headerRows()...); err != nil {
		return nil, fmt.Errorf("register header: %w", err)
	}
	if err := m.RegisterFooter(footerRows()...); err != nil {
		return nil, fmt.Errorf("register footer: %w", err)
	}

	m.AddRows(overviewRows()...)
	m.AddRows(pageBreak())
	m.AddRows(componentRows()...)
	m.AddRows(pageBreak())
	m.AddRows(gridRows()...)
	m.AddRows(pageBreak())
	m.AddRows(htmlRows(cfg.MaxGridSize)...)
	m.AddRows(pageBreak())
	m.AddRows(testingMetricsRows()...)
	m.AddRows(pageBreak())
	m.AddRows(useCaseRows()...)
	m.AddRows(pageBreak())
	m.AddRows(invoiceExampleRows()...)
	m.AddRows(pageBreak())
	m.AddRows(installRows()...)
	return m, nil
}

func headerRows() []core.Row {
	return []core.Row{
		row.New(6).Add(
			text.NewCol(6, "PAPER", props.Text{
				Family: serifFont,
				Style:  fontstyle.Bold,
				Size:   9,
				Color:  brand,
			}),
			text.NewCol(6, "Go PDF documents from components and HTML", props.Text{
				Family: fontfamily.Courier,
				Size:   7,
				Align:  align.Right,
				Color:  muted,
			}),
		),
		row.New(1.2).Add(col.New(12).Add(line.New(props.Line{
			Color:     borderC,
			Thickness: 0.25,
		}))),
	}
}

func footerRows() []core.Row {
	return []core.Row{
		row.New(1).Add(col.New(12).Add(line.New(props.Line{
			Color:     borderC,
			Thickness: 0.2,
		}))),
		row.New(4).Add(text.NewCol(12, "Generated by go run ./cmd/paper-showcase", props.Text{
			Family: fontfamily.Courier,
			Size:   6.5,
			Color:  muted,
		})),
	}
}

func overviewRows() []core.Row {
	return []core.Row{
		heroRow(),
		spacer(5),
		row.New(34).Add(
			codeSnippetCol(6, "main.go - one call", `package main

import "github.com/avdoseferovic/paper"

func main() {
  pdf, _ := paper.FromHTML(invoiceHTML)
  _ = pdf.Save("invoice.pdf")
}`, teal),
			codeSnippetCol(6, "layout.go - components", `doc := paper.New(cfg)
doc.AddRows(row.New(12).Add(
  col.New(8).Add(title),
  col.New(4).Add(qrCode),
))
pdf, _ := doc.Generate()`, blue),
		),
		spacer(6),
		sectionTitle("Two Authoring Paths", "Start from HTML in one call, or compose deterministic documents with rows, columns, and typed components."),
		row.New(52).Add(
			authoringPathCard(6, "HTML -> PDF", "Bring existing templates and fragments. Paper translates supported HTML and CSS into a print-ready PDF document.", `pdf, err := paper.FromHTML(tmpl)
if err != nil { return err }
_ = pdf.Save("invoice.pdf")`, teal, []string{"templates", "fragments", "CSS-aware"}),
			authoringPathCard(6, "Component grid", "Build explicit document layouts with a 12-column grid. Every primitive is inspectable and reusable in tests.", `m.AddRows(row.New(12).Add(
  col.New(6).Add(header),
  col.New(6).Add(total),
))`, blue, []string{"12 columns", "typed", "testable"}),
		),
		spacer(5),
		row.New(16).Add(
			outputChip(2, ".Save()", "write to disk"),
			outputChip(2, ".Bytes()", "raw bytes"),
			outputChip(2, ".Base64()", "API payloads"),
			outputChip(2, ".Merge()", "combine PDFs"),
			outputChip(4, "+ HTML fragments", "mix markup inside the component grid"),
		),
	}
}

type svgDiagramSpec struct {
	title    string
	subtitle string
	path     string
	focus    string
	route    string
	inspect  string
	accent   *props.Color
}

func svgDiagramRows() []core.Row {
	specs := []svgDiagramSpec{
		{
			title:    "SVG Diagram: Component Model",
			subtitle: "A vector overview of how Paper composes documents from pages, rows, columns, and components.",
			path:     "docs/assets/images/showcase/paper-component-model.svg",
			focus:    "Paper values compose top down: document, repeated pages, stacked rows, columns, then components.",
			route:    "The SVG is loaded as a direct image component and rasterized before PDF registration.",
			inspect:  "Look for measured rows, normalized column units, and the final component layer.",
			accent:   blue,
		},
		{
			title:    "SVG Diagram: Grid and Page Flow",
			subtitle: "The grid diagram shows margins, repeated header/footer rows, fixed and auto rows, and overflow.",
			path:     "docs/assets/images/showcase/paper-grid-flow.svg",
			focus:    "Rows decide vertical flow. Columns only divide the useful width inside each row.",
			route:    "The provider accepts extension.Svg, normalizes to PNG internally, then places it in the grid.",
			inspect:  "The overflow arrow mirrors the page-break behavior used by the generated showcase itself.",
			accent:   teal,
		},
		{
			title:    "SVG Diagram: HTML Pipeline",
			subtitle: "The HTML pipeline diagram connects markup, CSS, translator stages, and final PDF output.",
			path:     "docs/assets/images/showcase/paper-html-pipeline.svg",
			focus:    "HTML is not a screenshot path. It becomes the same Paper primitives as hand-built Go rows.",
			route:    "HTML SVGs and direct SVG images now share the same pure-Go rasterization helper.",
			inspect:  "The pipeline is the same path used by htmlcomponent.New elsewhere in this PDF.",
			accent:   amber,
		},
	}

	rows := make([]core.Row, 0, len(specs)*10)
	for i, spec := range specs {
		rows = append(rows, svgDiagramPage(spec)...)
		if i < len(specs)-1 {
			rows = append(rows, pageBreak())
		}
	}
	return rows
}

func svgDiagramPage(spec svgDiagramSpec) []core.Row {
	return []core.Row{
		sectionTitle(spec.title, spec.subtitle),
		spacer(4),
		svgDiagramImage(spec),
		spacer(5),
		row.New().Add(col.New(12).Add(svgDiagramNotesTable(spec))),
		spacer(5),
		thinRule(),
		spacer(4),
		row.New(37).Add(
			col.New(4).Add(text.New("Source", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: spec.accent}),
				text.New("These are checked-in SVG assets under docs/assets/images/showcase.", props.Text{Top: 8, Right: 5, Size: 7.7, Color: ink, VerticalPadding: 1.1})),
			col.New(4).Add(text.New("Image pipeline", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: teal}),
				text.New("The page uses image.NewFromBytes with extension.Svg, then the provider rasterizes internally.", props.Text{Top: 8, Right: 5, Size: 7.7, Color: ink, VerticalPadding: 1.1})),
			col.New(4).Add(text.New("Why SVG", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: brand}),
				text.New("The source stays crisp and editable while the PDF output remains provider-compatible.", props.Text{Top: 8, Right: 5, Size: 7.7, Color: ink, VerticalPadding: 1.1})),
		),
	}
}

func svgDiagramImage(spec svgDiagramSpec) core.Row {
	data, err := readShowcaseAsset(spec.path)
	if err != nil {
		panic(fmt.Errorf("read SVG diagram %s: %w", spec.path, err))
	}
	component := image.NewFromBytes(data, extension.Svg, props.Rect{Percent: 100, Center: true})
	return row.New().Add(col.New(12).Add(component))
}

func readShowcaseAsset(path string) ([]byte, error) {
	var lastErr error
	for _, root := range []string{".", "..", "../.."} {
		candidate := filepath.Join(root, path)
		data, err := os.ReadFile(candidate)
		if err == nil {
			return data, nil
		}
		lastErr = err
	}
	return nil, lastErr
}

func svgDiagramNotesTable(spec svgDiagramSpec) core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Focus", true, white), Style: tableHeaderStyle()},
			{Content: tableText("How it enters the PDF", true, white), Style: tableHeaderStyle()},
			{Content: tableText("What to inspect", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText(spec.focus, false, ink), Style: tableCellStyle(nil)},
			{Content: tableText(spec.route, false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText(spec.inspect, false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.55, 1.65, 1.45}))
	if err != nil {
		panic(err)
	}
	return t
}

func heroRow() core.Row {
	return row.New(86).Add(
		col.New(7).Add(
			text.New("GO / PDF GENERATION", props.Text{
				Family: fontfamily.Courier,
				Style:  fontstyle.Bold,
				Size:   7,
				Top:    7,
				Left:   5,
				Color:  teal,
			}),
			text.New("Generate PDFs from HTML and Go components", props.Text{
				Family:          serifFont,
				Style:           fontstyle.Bold,
				Size:            22,
				Top:             18,
				Left:            5,
				Right:           8,
				VerticalPadding: 1.05,
				Color:           ink,
			}),
			text.New("A precise, testable document engine for production Go services.", props.Text{
				Family:          serifFont,
				Size:            11.5,
				Top:             46,
				Left:            5,
				Right:           9,
				VerticalPadding: 1.15,
				Color:           inkSoft,
			}),
			text.New("Render HTML in one call or compose explicit PDF pages from rows, columns, and reusable components.", props.Text{
				Family:          fontfamily.Helvetica,
				Size:            8,
				Top:             59,
				Left:            5,
				Right:           10,
				VerticalPadding: 1.25,
				Color:           muted,
			}),
			text.New("$ go get github.com/avdoseferovic/paper", props.Text{
				Family: fontfamily.Courier,
				Style:  fontstyle.Bold,
				Size:   7.4,
				Top:    75,
				Left:   5,
				Color:  teal,
			}),
		),
		heroInvoicePreview(),
	).WithStyle(&props.Cell{
		BackgroundColor: canvas,
		BorderType:      border.Full,
		BorderColor:     lineSoftC,
		BorderThickness: 0.25,
		BorderRadius:    3,
	})
}

func heroInvoicePreview() core.Col {
	return col.New(5).Add(
		text.New("Invoice", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 16, Top: 7, Left: 5, Color: ink}),
		text.New("NO. INV-2026-0481", props.Text{Family: fontfamily.Courier, Size: 6.2, Top: 17, Left: 5, Color: muted}),
		code.NewQr("https://github.com/avdoseferovic/paper", props.Rect{Top: 6, Left: 37, Percent: 20}),
		text.New("BILLED TO", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 5.8, Top: 27, Left: 5, Color: faint}),
		text.New("Northwind Trading Co.", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 7.2, Top: 33, Left: 5, Color: inkSoft}),
		text.New("ISSUED", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 5.8, Top: 27, Left: 36, Color: faint}),
		text.New("June 8, 2026", props.Text{Family: fontfamily.Helvetica, Size: 7.2, Top: 33, Left: 36, Color: inkSoft}),
		text.New("ITEM", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 5.6, Top: 45, Left: 5, Color: faint}),
		text.New("AMOUNT", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 5.6, Top: 45, Align: align.Right, Right: 5, Color: faint}),
		text.New("Document API - Team", props.Text{Family: fontfamily.Helvetica, Size: 6.7, Top: 53, Left: 5, Color: inkSoft}),
		text.New("$480.00", props.Text{Family: fontfamily.Courier, Size: 6.7, Top: 53, Align: align.Right, Right: 5, Color: ink}),
		text.New("Rendering credits", props.Text{Family: fontfamily.Helvetica, Size: 6.7, Top: 61, Left: 5, Color: inkSoft}),
		text.New("$240.00", props.Text{Family: fontfamily.Courier, Size: 6.7, Top: 61, Align: align.Right, Right: 5, Color: ink}),
		text.New("TOTAL DUE", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 6, Top: 74, Left: 5, Color: muted}),
		text.New("$840.00", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 14, Top: 70, Align: align.Right, Right: 5, Color: ink}),
	).WithStyle(&props.Cell{
		BackgroundColor: white,
		BorderType:      border.Full,
		BorderColor:     borderC,
		BorderThickness: 0.25,
		BorderRadius:    2,
		MarginTop:       6,
		MarginRight:     5,
		MarginBottom:    6,
	})
}

func codeSnippetCol(size int, label, value string, accent *props.Color) core.Col {
	components := []core.Component{
		text.New(label, props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 6.5, Top: 3, Left: 4, Color: muted}),
	}
	for i, line := range strings.Split(strings.Trim(value, "\n"), "\n") {
		color := inkSoft
		if strings.Contains(line, "paper.") || strings.Contains(line, "doc.") || strings.Contains(line, "m.") {
			color = accent
		}
		components = append(components, text.New(line, props.Text{
			Family: fontfamily.Courier,
			Size:   6.3,
			Top:    10 + float64(i)*3.3,
			Left:   4,
			Right:  4,
			Color:  color,
		}))
	}
	return col.New(size).Add(components...).WithStyle(codePanelStyle())
}

func authoringPathCard(size int, title, body, snippet string, accent *props.Color, chips []string) core.Col {
	components := []core.Component{
		text.New(title, props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 14, Top: 5, Left: 5, Color: ink}),
		text.New(body, props.Text{Family: fontfamily.Helvetica, Size: 7.7, Top: 17, Left: 5, Right: 5, VerticalPadding: 1.2, Color: muted}),
	}
	for i, line := range strings.Split(strings.Trim(snippet, "\n"), "\n") {
		components = append(components, text.New(line, props.Text{
			Family: fontfamily.Courier,
			Size:   6.1,
			Top:    31 + float64(i)*3.1,
			Left:   5,
			Right:  5,
			Color:  inkSoft,
		}))
	}
	for i, chip := range chips {
		components = append(components, text.New(chip, props.Text{
			Family: fontfamily.Courier,
			Style:  fontstyle.Bold,
			Size:   5.4,
			Top:    45,
			Left:   5 + float64(i)*23,
			Color:  accent,
		}))
	}
	return col.New(size).Add(components...).WithStyle(cardStyle(white, borderC))
}

func outputChip(size int, command, label string) core.Col {
	return col.New(size).Add(
		text.New(command, props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 7, Top: 3, Align: align.Center, Color: teal}),
		text.New(label, props.Text{Family: fontfamily.Helvetica, Size: 6.2, Top: 9, Align: align.Center, Left: 2, Right: 2, Color: muted}),
	).WithStyle(cardStyle(white, borderC))
}

func paperShadow() props.Shadow {
	return props.Shadow{
		OffsetY:    1.4,
		BlurRadius: 3.5,
		Spread:     0.1,
		Color:      rgba(40, 30, 20, 0.12),
	}
}

func codePanelStyle() *props.Cell {
	return &props.Cell{
		BackgroundColor: codeBg,
		BorderType:      border.Full,
		BorderColor:     borderC,
		BorderThickness: 0.25,
		BorderRadius:    2,
		MarginLeft:      0.8,
		MarginRight:     0.8,
	}
}

func overviewMatrixTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Surface", true, white), Style: tableHeaderStyle()},
			{Content: tableText("What it shows", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Typical output", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Components", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Explicit rows, columns, and typed primitives.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Operational PDFs and forms.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("HTML", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Markup translated into Paper rows.", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Rich fragments and imported content.", false, ink), Style: tableCellStyle(softTeal)},
		},
		{
			{Content: tableText("Document", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Headers, footers, page numbers, metadata, and bytes.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Files, streams, base64, and merged PDFs.", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.05, 2.1, 1.9}))
	if err != nil {
		panic(err)
	}
	return t
}

func componentRows() []core.Row {
	return []core.Row{
		sectionTitle("Component Library", "Every document primitive can be dropped into a column, composed into larger blocks, and inspected in tests."),
		row.New(34).Add(
			componentColumn(3, "Text", teal,
				text.New("Headings, labels, and body copy wrap inside the available column width.", props.Text{Top: 12, Left: 4, Right: 4, Size: 7.2, Color: inkSoft, VerticalPadding: 1.1}),
			),
			componentColumn(3, "Rich text", blue,
				richtext.New([]props.RichRun{
					{Text: "Mix ", Size: 7.2},
					{Text: "bold", Style: fontstyle.Bold, Color: ink, Size: 7.2},
					{Text: ", ", Size: 7.2},
					{Text: "links", Underline: true, Color: teal, Size: 7.2},
					{Text: ", and accents.", Size: 7.2},
				}, props.RichText{Top: 13, Left: 4, Right: 4, LineHeight: 1.15}),
			),
			componentColumn(3, "Images", green,
				image.NewFromFile("docs/assets/images/logosmall.png", props.Rect{Top: 11, Left: 25, Percent: 28}),
			),
			componentColumn(3, "Tables", amber,
				text.New("Item      Qty   Total", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 13, Left: 4, Color: faint}),
				text.New("API        1    $480", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 20, Left: 4, Color: inkSoft}),
				text.New("Credits   12k  $240", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 27, Left: 4, Color: inkSoft}),
			),
		),
		spacer(3),
		row.New(34).Add(
			componentColumn(3, "QR codes", teal,
				code.NewQr("https://github.com/avdoseferovic/paper", props.Rect{Top: 10, Left: 20, Percent: 35}),
			),
			componentColumn(3, "Barcodes", blue,
				code.NewBar("PAPER-2026", props.Barcode{Top: 16, Left: 9, Percent: 70, Proportion: props.Proportion{Width: 12, Height: 1.6}}),
			),
			componentColumn(3, "Data Matrix", green,
				code.NewMatrix("PAPER-2026-DM", props.Rect{Top: 10, Left: 20, Percent: 35}),
			),
			componentColumn(3, "Checkboxes", amber,
				checkbox.New("Approved", props.Checkbox{Checked: true, Top: 14, Left: 5, Size: 3.6}),
				checkbox.New("Pending", props.Checkbox{Top: 23, Left: 5, Size: 3.6}),
			),
		),
		spacer(3),
		row.New(34).Add(
			componentColumn(3, "Signatures", teal,
				signature.New("Avdo S.", props.Signature{FontColor: ink, LineColor: borderC, LineThickness: 0.3}),
			),
			componentColumn(3, "Lines", blue,
				line.New(props.Line{Color: ink, Thickness: 0.3, OffsetPercent: 46, SizePercent: 72}),
				line.New(props.Line{Color: faint, Thickness: 0.35, Style: linestyle.Dashed, OffsetPercent: 66, SizePercent: 72}),
			),
			componentColumn(3, "Page numbers", green,
				text.New("Page 3 of 12", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 8, Top: 17, Align: align.Center, Color: inkSoft}),
			),
			componentColumn(3, "Headers & footers", amber,
				text.New("HEADER", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 10, Align: align.Center, Color: muted}),
				text.New("main content region", props.Text{Family: fontfamily.Helvetica, Size: 6.7, Top: 18, Align: align.Center, Color: inkSoft}),
				text.New("FOOTER", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 28, Align: align.Center, Color: teal}),
			),
		),
		spacer(6),
		sectionTitle("Components stay inspectable", "The rendered page and the test structure come from the same rows, columns, and components."),
		row.New().Add(col.New(12).Add(componentPlacementTable())),
	}
}

func componentColumn(size int, title string, accent *props.Color, components ...core.Component) core.Col {
	all := make([]core.Component, 0, len(components)+1)
	all = append(all, text.New(title, props.Text{
		Family: fontfamily.Helvetica,
		Style:  fontstyle.Bold,
		Size:   9,
		Top:    1,
		Left:   4,
		Color:  accent,
	}))
	all = append(all, components...)
	return col.New(size).Add(all...).WithStyle(cardStyle(white, borderC))
}

func componentPlacementTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Component", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Placement behavior", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Practical note", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Text / rich text", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Measures wrapping inside the available column width.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Use auto rows for variable-length body copy.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Images / codes", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("Scale from the cell dimensions and local offsets.", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("Reserve clear space around scannable content.", false, ink), Style: tableCellStyle(softGold)},
		},
		{
			{Content: tableText("Tables", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Compute row height from their cell contents.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Good for dense facts, ledgers, and compatibility matrices.", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.25, 2.15, 2.05}))
	if err != nil {
		panic(err)
	}
	return t
}

func textFlowRows() []core.Row {
	return []core.Row{
		sectionTitle("Text, Flow, and Spacing", "Use text and rich text as measured components, then compose them with rows."),
		row.New(42).Add(
			col.New(7).Add(
				text.New("Narrative content", props.Text{
					Family: fontfamily.Helvetica,
					Style:  fontstyle.Bold,
					Size:   10,
					Color:  brand,
				}),
				richtext.New([]props.RichRun{
					{Text: "Paper can render regular text beside "},
					{Text: "rich inline runs", Style: fontstyle.Bold, Color: blue},
					{Text: ", links, emphasized labels, and measured wrapping without leaving the grid model."},
				}, props.RichText{Top: 8, Right: 8, LineHeight: 1.18}),
				text.New("Rows can be fixed height for predictable layouts or auto height when content determines vertical space.", props.Text{
					Family:          fontfamily.Helvetica,
					Size:            8,
					Top:             25,
					Right:           8,
					VerticalPadding: 1.1,
					Color:           muted,
				}),
			),
			col.New(5).Add(
				text.New("Alignment samples", props.Text{
					Family: fontfamily.Helvetica,
					Style:  fontstyle.Bold,
					Size:   10,
					Color:  brand,
				}),
				text.New("left aligned", props.Text{Top: 9, Size: 8, Color: ink}),
				text.New("center aligned", props.Text{Top: 17, Size: 8, Align: align.Center, Color: ink}),
				text.New("right aligned", props.Text{Top: 25, Size: 8, Align: align.Right, Color: ink}),
				text.New("Use text props for alignment, indentation, top offsets, and wrapping.", props.Text{Top: 34, Size: 7.2, Color: muted}),
			),
		),
		thinRule(),
		spacer(3),
		row.New().Add(col.New(12).Add(textFlowTable())),
		spacer(5),
		row.New(34).Add(
			col.New(6).Add(
				text.New("Composition pattern", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: teal}),
				text.New("Rows stack top to bottom. Columns provide horizontal regions. Components are measured before render so text wraps consistently.", props.Text{
					Top:             9,
					Right:           8,
					Size:            8,
					VerticalPadding: 1.1,
					Color:           ink,
				}),
			),
			col.New(6).Add(
				text.New("Useful for", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: amber}),
				text.New("Reports, letters, invoices, approvals, generated forms, and HTML fragments that need predictable PDF output.", props.Text{
					Top:             9,
					Right:           6,
					Size:            8,
					VerticalPadding: 1.1,
					Color:           ink,
				}),
			),
		),
		thinRule(),
		spacer(4),
		row.New(40).Add(
			col.New(5).Add(
				text.New("Type scale", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: brand}),
				text.New("Section heading", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 13, Top: 8, Color: brand}),
				text.New("Subheading", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Top: 18, Color: teal}),
				text.New("Body copy with measured wrapping and steady line height.", props.Text{Family: fontfamily.Helvetica, Size: 8, Top: 28, Right: 5, Color: ink}),
			),
			col.New(7).Add(
				text.New("Measured text output", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: brand}),
				text.New("The same paragraph can sit beside narrow side content, wrap inside a table cell, or flow through a full-width narrative section without changing the component contract.", props.Text{
					Top:             9,
					Right:           4,
					Size:            8,
					Color:           ink,
					VerticalPadding: 1.2,
				}),
			),
		),
	}
}

func textFlowTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Need", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Component", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Example", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Single run", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("text.New", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Headings, labels, body copy, page metadata.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Inline styles", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("richtext.New", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Bold spans, colored runs, underlined links.", false, ink), Style: tableCellStyle(softBlue)},
		},
		{
			{Content: tableText("Visual separation", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("line.New", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Section rules, dividers, and lightweight hierarchy.", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.1, 1.15, 2.7}))
	if err != nil {
		panic(err)
	}
	return t
}

func reportExampleRows() []core.Row {
	return []core.Row{
		sectionTitle("Report-Style Page", "A compact example that combines layout, data, checks, codes, and approval."),
		row.New(26).Add(
			col.New(7).Add(
				text.New("Site Readiness Report", props.Text{
					Family: fontfamily.Helvetica,
					Style:  fontstyle.Bold,
					Size:   16,
					Color:  brand,
				}),
				text.New("North Facility / Prepared 2026-06-08 / Ref PAPER-2026", props.Text{
					Family: fontfamily.Helvetica,
					Size:   8,
					Top:    12,
					Color:  muted,
				}),
			),
			col.New(2).Add(code.NewQr("PAPER-READINESS-2026", props.Rect{Percent: 48, Center: true})),
			col.New(3).Add(code.NewBar("PAPER-2026", props.Barcode{
				Percent:    58,
				Center:     true,
				Proportion: props.Proportion{Width: 12, Height: 1.6},
			})),
		).WithStyle(&props.Cell{
			BackgroundColor: canvas,
			BorderRadius:    3,
			PaddingLeft:     2,
		}),
		spacer(5),
		row.New().Add(col.New(12).Add(reportSnapshotTable())),
		spacer(5),
		row.New(34).Add(
			col.New(6).Add(
				text.New("Checklist", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: brand}),
				checkbox.New("Source data reviewed", props.Checkbox{Checked: true, Top: 10, Size: 3.8}),
				checkbox.New("Assets resolved from disk", props.Checkbox{Checked: true, Top: 18, Size: 3.8}),
				checkbox.New("Generated PDF visually inspected", props.Checkbox{Top: 26, Size: 3.8}),
			),
			col.New(6).Add(
				text.New("Approval", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: brand}),
				signature.New("Prepared by Paper", props.Signature{
					FontColor:     teal,
					LineColor:     teal,
					LineThickness: 0.35,
				}),
			),
		),
		thinRule(),
		spacer(3),
		row.New().Add(col.New(12).Add(reportLineItemTable())),
		spacer(5),
		row.New().Add(col.New(12).Add(reportAuditTable())),
		spacer(5),
		row.New(24).Add(
			col.New(4).Add(text.New("Reusable bands", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: blue}),
				text.New("Headers, data tables, and approval rows can be assembled as reusable row groups.", props.Text{Top: 8, Right: 5, Size: 7.8, Color: ink})),
			col.New(4).Add(text.New("Human + machine", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: teal}),
				text.New("QR and barcode components carry references alongside readable report content.", props.Text{Top: 8, Right: 5, Size: 7.8, Color: ink})),
			col.New(4).Add(text.New("Stable output", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: amber}),
				text.New("Page numbers, margins, and footer rules stay consistent across generated pages.", props.Text{Top: 8, Right: 5, Size: 7.8, Color: ink})),
		),
	}
}

func reportSnapshotTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Metric", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Value", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Status", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Notes", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Pages generated", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("8", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("OK", false, green), Style: tableCellStyle(nil)},
			{Content: tableText("Page numbers and repeated header/footer enabled.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Assets", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Images + codes", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("OK", false, green), Style: tableCellStyle(softTeal)},
			{Content: tableText("Logo, QR, and barcode components render from the same grid.", false, ink), Style: tableCellStyle(softTeal)},
		},
		{
			{Content: tableText("Layout", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Rows + columns", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("OK", false, green), Style: tableCellStyle(nil)},
			{Content: tableText("Tables, checks, and signatures share predictable cells.", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.2, 1.1, 0.8, 2.5}))
	if err != nil {
		panic(err)
	}
	return t
}

func reportAuditTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Event", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Actor", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Timestamp", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Result", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Data assembled", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Report job", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("2026-06-08 09:00", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Ready", false, green), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("PDF generated", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Paper", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("2026-06-08 09:01", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Saved", false, green), Style: tableCellStyle(softBlue)},
		},
	}, table.WithColumnWidths([]float64{1.4, 1.0, 1.35, 0.9}))
	if err != nil {
		panic(err)
	}
	return t
}

func reportLineItemTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Output", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Component mix", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Why it matters", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Operational reports", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("text, table, image, signature", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Stable structure with dynamic content.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Generated forms", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("checkbox, barcode, richtext", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("Machine-readable references and human approval in one file.", false, ink), Style: tableCellStyle(softGold)},
		},
	}, table.WithColumnWidths([]float64{1.35, 1.5, 2.6}))
	if err != nil {
		panic(err)
	}
	return t
}

func gridBehaviorTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Case", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Behavior", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Why it matters", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Exact fit", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Column units add to the configured grid size.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("The row fills the useful page width.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Underflow", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Unused grid units remain blank space.", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Useful for indents, side notes, and sparse layouts.", false, ink), Style: tableCellStyle(softTeal)},
		},
		{
			{Content: tableText("Auto height", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Largest child height defines the row.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Variable text and tables can remain deterministic.", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.0, 2.2, 2.2}))
	if err != nil {
		panic(err)
	}
	return t
}

func gridRows() []core.Row {
	return []core.Row{
		sectionTitle("Layout Model", "Rows and columns on a 12-column grid, resolved to exact points on the PDF page."),
		row.New(23).Add(
			cardCol(4, "Default denominator", "Paper defaults to a 12-unit grid.", softBlue, blue),
			cardCol(4, "Column widths", "col.New(3) gets 3/12 of the row width.", softTeal, teal),
			cardCol(4, "Auto height", "row.New() measures child content before rendering.", softGold, amber),
		),
		spacer(5),
		gridExampleRow("col.New(12)", []gridCellSpec{{12, "12", blue}}),
		spacer(2),
		gridExampleRow("col.New(6), col.New(6)", []gridCellSpec{{6, "6", teal}, {6, "6", green}}),
		spacer(2),
		gridExampleRow("col.New(4), col.New(4), col.New(4)", []gridCellSpec{{4, "4", amber}, {4, "4", red}, {4, "4", blue}}),
		spacer(2),
		gridExampleRow("four equal columns", []gridCellSpec{{3, "3", blue}, {3, "3", teal}, {3, "3", amber}, {3, "3", red}}),
		spacer(6),
		sectionTitle("How placement works", "Paper measures rows before rendering and creates new pages when the useful area is full."),
		row.New(18).Add(
			col.New(4).Add(text.New("1. Compute useful page area after margins, header, and footer.", props.Text{Top: 1, Right: 4, Size: 8, Color: ink})),
			col.New(4).Add(text.New("2. Measure each row. Rows that overflow move to a new page.", props.Text{Top: 1, Right: 4, Size: 8, Color: ink})),
			col.New(4).Add(text.New("3. Normalize column units against MaxGridSize.", props.Text{Top: 1, Right: 4, Size: 8, Color: ink})),
		),
		thinRule(),
		spacer(4),
		row.New().Add(col.New(12).Add(gridBehaviorTable())),
		spacer(5),
		row.New(23).Add(
			col.New(3).Add(text.New("Nested rows", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: blue}),
				text.New("Components can contain translated HTML or tables inside normal columns.", props.Text{Top: 8, Right: 4, Size: 7.5, Color: ink})),
			col.New(3).Add(text.New("Auto rows", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: teal}),
				text.New("Measured content determines height before drawing begins.", props.Text{Top: 8, Right: 4, Size: 7.5, Color: ink})),
			col.New(3).Add(text.New("Manual rows", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: amber}),
				text.New("Fixed heights keep reports and form regions predictable.", props.Text{Top: 8, Right: 4, Size: 7.5, Color: ink})),
			col.New(3).Add(text.New("Page flow", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: red}),
				text.New("Rows that do not fit continue on the next page with header and footer.", props.Text{Top: 8, Right: 4, Size: 7.5, Color: ink})),
		),
	}
}

func htmlRows(gridSize int) []core.Row {
	return []core.Row{
		sectionTitle("HTML Pipeline", "HTML in, structured Paper rows out, then rendered through the same PDF provider."),
		row.New(32).Add(
			infoCol(4, "Full document", "paper.FromHTML returns a generated PDF document from one HTML string.", blue),
			infoCol(4, "Append rows", "m.AddHTML parses HTML into rows using the active Paper configuration.", teal),
			infoCol(4, "Column fragment", "htmlcomponent.New wraps translated rows as a regular component.", amber),
		),
		spacer(5),
		sectionTitle("HTML support snapshot", "The translator maps common HTML and CSS features onto Paper primitives."),
		row.New().Add(col.New(12).Add(htmlSupportTable())),
		spacer(5),
		row.New().Add(col.New(12).Add(htmlPipelineTable())),
		spacer(5),
		thinRule(),
		spacer(4),
		row.New(31).Add(
			col.New(4).Add(text.New("Inline content", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: blue}),
				text.New("Paragraphs, headings, strong/emphasis, links, and colored text become text or rich text runs.", props.Text{Top: 8, Right: 5, Size: 7.8, Color: ink, VerticalPadding: 1.1})),
			col.New(4).Add(text.New("Block layout", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: teal}),
				text.New("Flex rows and common block spacing are mapped onto Paper rows and grid columns.", props.Text{Top: 8, Right: 5, Size: 7.8, Color: ink, VerticalPadding: 1.1})),
			col.New(4).Add(text.New("Document fit", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: amber}),
				text.New("Translated rows use the same page measurement, break, header, and footer behavior as hand-built rows.", props.Text{Top: 8, Right: 5, Size: 7.8, Color: ink, VerticalPadding: 1.1})),
		),
		pageBreak(),
		sectionTitle("HTML Rendered Output", "This fragment is parsed through pkg/components/html and rendered as Paper rows."),
		htmlShowcaseBlock(gridSize),
		spacer(5),
		row.New().Add(col.New(12).Add(htmlRenderedNotesTable())),
		spacer(5),
		thinRule(),
		spacer(4),
		row.New(32).Add(
			col.New(6).Add(text.New("Why this page matters", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: brand}),
				text.New("The HTML example is not a screenshot. It is parsed into Paper components and rendered by the same provider pipeline as the rest of the document.", props.Text{Top: 9, Right: 7, Size: 8, Color: ink, VerticalPadding: 1.1})),
			col.New(6).Add(text.New("What to inspect", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 10, Color: teal}),
				text.New("The panel border, flex-style KPI row, table header, cell borders, and text wrapping all come from translated HTML and CSS.", props.Text{Top: 9, Right: 7, Size: 8, Color: ink, VerticalPadding: 1.1})),
		),
	}
}

func htmlShowcaseBlock(gridSize int) core.Row {
	component, err := htmlcomponent.New(`
<style>
.panel { border: 1px solid #e2dbd1; border-radius: 4px; padding: 6px; background: #fcfaf7; }
.kpis { display: flex; gap: 6px; margin: 5px 0; }
.kpi { flex: 1; padding: 5px; background: #fbf0ec; border-left: 3px solid #be4f36; font-size: 10px; }
table { width: 100%; border-collapse: collapse; margin-top: 5px; font-size: 10px; }
th { background: #3a322b; color: white; font-size: 10px; }
td, th { border: 1px solid #e2dbd1; padding: 4px; }
</style>
<div class="panel">
  <h2 style="font-size:22px; margin:0 0 3px 0;">Rendered HTML Fragment</h2>
  <p style="font-size:10px; margin:0 0 5px 0;">Paper translates supported tags and CSS into the same row, column, text, table, and style primitives used elsewhere in this PDF.</p>
  <div class="kpis">
    <div class="kpi"><strong>Blocks</strong><br>headings, paragraphs, lists</div>
    <div class="kpi"><strong>Layout</strong><br>tables and flex rows</div>
    <div class="kpi"><strong>Styles</strong><br>colors, borders, spacing</div>
  </div>
  <table>
    <tr><th>HTML</th><th>Paper output</th></tr>
    <tr><td>&lt;p&gt;, &lt;strong&gt;, &lt;em&gt;</td><td>rich text runs</td></tr>
    <tr><td>display:flex</td><td>grid columns</td></tr>
    <tr><td>table</td><td>table component cells</td></tr>
  </table>
</div>`, htmlcomponent.WithGridSize(gridSize), htmlcomponent.WithContentWidth(176))
	if err != nil {
		panic(err)
	}
	return row.New().Add(col.New(12).Add(component))
}

func htmlPipelineTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Stage", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Input", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Paper primitive", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Parse", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("DOM nodes and CSS declarations", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Intermediate block tree", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Translate", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Blocks, flex, tables, inline runs", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("Rows, columns, text, rich text, tables", false, ink), Style: tableCellStyle(softTeal)},
		},
		{
			{Content: tableText("Render", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Measured Paper rows", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("PDF cells on the page", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{0.9, 2.1, 2.1}))
	if err != nil {
		panic(err)
	}
	return t
}

func htmlRenderedNotesTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Rendered feature", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Visible result", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Backed by", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Panel styling", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Border, radius, padding, and background.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Cell styles", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Flex KPI row", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Three equal columns with gaps.", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Grid columns", false, ink), Style: tableCellStyle(softBlue)},
		},
		{
			{Content: tableText("HTML table", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Header row, borders, and data rows.", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Table component", false, ink), Style: tableCellStyle(nil)},
		},
	}, table.WithColumnWidths([]float64{1.3, 2.15, 1.4}))
	if err != nil {
		panic(err)
	}
	return t
}

func testingMetricsRows() []core.Row {
	return []core.Row{
		sectionTitle("Testing and Metrics", "Inspect the component tree before rendering, then track generation behavior after each run."),
		row.New(74).Add(
			treeSnapshotCol(7),
			metricsSnapshotCol(5),
		),
		spacer(6),
		row.New(28).Add(
			cardCol(4, "Deterministic snapshots", "Assert structure without image diffs. Rows, columns, tables, and codes all appear in the tree.", softBlue, blue),
			cardCol(4, "Generation timing", "Optional metrics expose build phases, add-row timings, page creation, and output size.", softTeal, teal),
			cardCol(4, "Visual verification", "Render the final PDF pages when layout or assets change, then keep the source as normal Go.", softGold, amber),
		),
	}
}

func treeSnapshotCol(size int) core.Col {
	lines := []string{
		"Document a4 portrait",
		"+-- Header",
		"|   +-- Row [12]",
		"+-- Row [8,4]",
		"|   +-- Text \"Invoice\" ok",
		"|   +-- QRCode 88x88 ok",
		"+-- Table 4 rows",
		"+-- Footer PageNumber",
	}
	components := []core.Component{
		text.New("doc.Tree() - deterministic snapshot", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 7, Top: 4, Left: 5, Color: muted}),
	}
	for i, line := range lines {
		color := inkSoft
		if strings.Contains(line, "Document") || strings.Contains(line, "Text") || strings.Contains(line, "Table") {
			color = blue
		}
		components = append(components, text.New(line, props.Text{
			Family: fontfamily.Courier,
			Size:   7,
			Top:    14 + float64(i)*5.2,
			Left:   6,
			Color:  color,
		}))
	}
	return col.New(size).Add(components...).WithStyle(codePanelStyle())
}

func metricsSnapshotCol(size int) core.Col {
	return col.New(size).Add(
		text.New("paper.Metrics() - last run", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 7, Top: 4, Left: 5, Color: muted}),
		text.New("18 ms", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 18, Top: 16, Left: 7, Color: ink}),
		text.New("generation time", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 28, Left: 7, Color: faint}),
		text.New("7", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 18, Top: 16, Left: 39, Color: ink}),
		text.New("components", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 28, Left: 39, Color: faint}),
		text.New("1", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 18, Top: 42, Left: 7, Color: ink}),
		text.New("page", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 54, Left: 7, Color: faint}),
		text.New("42 kb", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 18, Top: 42, Left: 39, Color: ink}),
		text.New("output size", props.Text{Family: fontfamily.Courier, Size: 5.8, Top: 54, Left: 39, Color: faint}),
		text.New("throughput  1,240 docs/sec", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 7, Top: 65, Left: 7, Color: teal}),
	).WithStyle(cardStyle(white, borderC))
}

func useCaseRows() []core.Row {
	return []core.Row{
		sectionTitle("Use Cases", "Built for the documents Go services generate on demand and at volume."),
		row.New(44).Add(
			useCaseCard(2, "Invoices", "totals, tax, QR pay"),
			useCaseCard(2, "Reports", "tables, charts, pages"),
			useCaseCard(2, "Forms", "checks, fields, signs"),
			useCaseCard(2, "Labels", "barcodes, batches"),
			useCaseCard(2, "Certificates", "signatures, seals"),
			useCaseCard(2, "Contracts", "clauses, appendices"),
		),
		spacer(6),
		row.New(36).Add(
			cardCol(3, "Production APIs", "Return bytes, base64 payloads, or files from the same document object.", softBlue, blue),
			cardCol(3, "Document automation", "Generate customer-facing PDFs from queue workers and service jobs.", softTeal, teal),
			cardCol(3, "HTML migration", "Reuse existing markup while moving toward typed component layouts.", softGold, amber),
			cardCol(3, "Audit-friendly", "Keep the generated structure testable and repeatable across releases.", softRose, red),
		),
		spacer(5),
		row.New().Add(col.New(12).Add(overviewMatrixTable())),
	}
}

func useCaseCard(size int, name, detail string) core.Col {
	return col.New(size).Add(
		text.New(name, props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 8.2, Top: 23, Align: align.Center, Color: ink}),
		text.New(detail, props.Text{Family: fontfamily.Courier, Size: 5.7, Top: 30, Align: align.Center, Left: 2, Right: 2, Color: muted}),
		text.New("PDF", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 15, Top: 7, Align: align.Center, Color: teal}),
	).WithStyle(&props.Cell{
		BackgroundColor: white,
		BorderType:      border.Full,
		BorderColor:     borderC,
		BorderThickness: 0.25,
		BorderRadius:    2,
		MarginLeft:      0.6,
		MarginRight:     0.6,
	})
}

func invoiceExampleRows() []core.Row {
	return []core.Row{
		sectionTitle("Generated PDF Example", "A single invoice-style page using the same visual language as the showcase hero."),
		row.New(36).Add(
			col.New(7).Add(
				text.New("Paper Labs, Inc.", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 14, Top: 5, Left: 3, Color: ink}),
				text.New("120 Foundry Street, Suite 4 / Brooklyn, NY 11222 / hello@paperlabs.dev", props.Text{Family: fontfamily.Helvetica, Size: 7, Top: 15, Left: 3, Right: 8, Color: muted, VerticalPadding: 1.12}),
			),
			col.New(3).Add(
				text.New("Invoice", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 22, Top: 4, Align: align.Right, Right: 2, Color: ink}),
				text.New("NO. INV-2026-0481", props.Text{Family: fontfamily.Courier, Size: 7, Top: 21, Align: align.Right, Right: 2, Color: teal}),
			),
			col.New(2).Add(code.NewQr("pay.paperlabs.dev/inv-0481", props.Rect{Percent: 45, Center: true})),
		).WithStyle(sheetHeaderStyle()),
		spacer(5),
		row.New(28).Add(
			invoiceMetaCol(3, "Billed to", "Northwind Trading Co. / Accounts Payable"),
			invoiceMetaCol(3, "Issue date", "June 8, 2026 / Due July 8, 2026"),
			invoiceMetaCol(3, "Terms", "Net 30 / PO-77-4521"),
			invoiceMetaCol(3, "Currency", "USD ($) / Account NW-00231"),
		),
		spacer(5),
		row.New().Add(col.New(12).Add(invoiceItemsTable())),
		spacer(6),
		row.New(45).Add(
			col.New(6).Add(
				text.New("Payment details", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 7, Top: 3, Left: 3, Color: faint}),
				text.New("Wire transfer or ACH within 30 days. Reference the invoice number on all remittances.", props.Text{Family: fontfamily.Helvetica, Size: 7.4, Top: 12, Left: 3, Right: 8, Color: muted, VerticalPadding: 1.2}),
				code.NewBar("INV-2026-0481", props.Barcode{Top: 29, Left: 3, Percent: 46, Proportion: props.Proportion{Width: 12, Height: 1.4}}),
			),
			col.New(6).Add(invoiceTotalsTable()),
		),
		spacer(5),
		row.New(38).Add(
			col.New(6).Add(
				text.New("Avdo S.", props.Text{Family: serifFont, Style: fontstyle.Italic, Size: 20, Top: 6, Left: 3, Color: ink}),
				text.New("Authorized - Paper Labs", props.Text{Family: fontfamily.Courier, Size: 6, Top: 25, Left: 3, Color: faint}),
			),
			col.New(6).Add(
				checkbox.New("Goods and services received in full", props.Checkbox{Checked: true, Top: 7, Left: 3, Size: 3.8}),
				checkbox.New("Amount verified against PO-77-4521", props.Checkbox{Checked: true, Top: 17, Left: 3, Size: 3.8}),
				checkbox.New("Recurring billing authorized", props.Checkbox{Top: 27, Left: 3, Size: 3.8}),
			),
		).WithStyle(sheetFooterStyle()),
	}
}

func invoiceMetaCol(size int, label, value string) core.Col {
	return col.New(size).Add(
		text.New(label, props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 6, Top: 3, Left: 3, Color: faint}),
		text.New(value, props.Text{Family: fontfamily.Helvetica, Size: 7.4, Top: 10, Left: 3, Right: 3, Color: inkSoft, VerticalPadding: 1.15}),
	).WithStyle(cardStyle(white, borderC))
}

func invoiceItemsTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Description", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Qty", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Unit price", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Amount", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Document API - Team plan", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("1", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("$480.00", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("$480.00", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Rendering credits", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("12k", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("$0.02", false, ink), Style: tableCellStyle(softTeal)},
			{Content: tableText("$240.00", false, ink), Style: tableCellStyle(softTeal)},
		},
		{
			{Content: tableText("Priority support", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("1", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("$120.00", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("$120.00", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Custom font embedding", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("3", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("$30.00", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("$90.00", false, ink), Style: tableCellStyle(softGold)},
		},
	}, table.WithColumnWidths([]float64{2.7, 0.6, 0.9, 0.9}))
	if err != nil {
		panic(err)
	}
	return t
}

func invoiceTotalsTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Subtotal", false, muted), Style: tableCellStyle(nil)},
			{Content: tableText("$930.00", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Volume discount (5%)", false, muted), Style: tableCellStyle(softTeal)},
			{Content: tableText("-$46.50", false, green), Style: tableCellStyle(softTeal)},
		},
		{
			{Content: tableText("Tax (NY 8.875%)", false, muted), Style: tableCellStyle(nil)},
			{Content: tableText("$78.41", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Total due", true, white), Style: tableHeaderStyle()},
			{Content: tableText("$961.91", true, white), Style: tableHeaderStyle()},
		},
	}, table.WithColumnWidths([]float64{1.6, 1.0}))
	if err != nil {
		panic(err)
	}
	return t
}

func sheetHeaderStyle() *props.Cell {
	return &props.Cell{
		BackgroundColor: white,
		BorderType:      border.Full,
		BorderColor:     borderC,
		BorderThickness: 0.25,
		BorderRadius:    2,
		PaddingTop:      2,
		PaddingBottom:   2,
	}
}

func sheetFooterStyle() *props.Cell {
	return &props.Cell{
		BackgroundColor:    white,
		BorderTopColor:     borderC,
		BorderTopThickness: 0.3,
		PaddingTop:         2,
	}
}

func installRows() []core.Row {
	return []core.Row{
		row.New(96).Add(
			col.New(12).Add(
				text.New("Install Paper", props.Text{Family: serifFont, Style: fontstyle.Bold, Size: 26, Top: 18, Align: align.Center, Color: white}),
				text.New("Ship documents that render exactly right.", props.Text{Family: serifFont, Style: fontstyle.Italic, Size: 15, Top: 39, Align: align.Center, Color: rgb(231, 166, 139)}),
				text.New("Add Paper to your Go service and generate production PDFs in a single import.", props.Text{Family: fontfamily.Helvetica, Size: 8.6, Top: 55, Align: align.Center, Color: rgb(207, 198, 188)}),
				text.New("$ go get github.com/avdoseferovic/paper", props.Text{Family: fontfamily.Courier, Style: fontstyle.Bold, Size: 10, Top: 72, Align: align.Center, Color: white}),
			),
		).WithStyle(&props.Cell{
			BackgroundColor: deepInk,
			BorderRadius:    3,
		}),
		spacer(8),
		row.New(34).Add(
			cardCol(4, "Docs", "Read examples for HTML, components, tables, codes, and generated output.", softBlue, blue),
			cardCol(4, "GitHub", "Use the repository examples as executable documentation for your service.", softTeal, teal),
			cardCol(4, "MIT License", "Build PDFs in Go without adding a browser runtime to production jobs.", softGold, amber),
		),
	}
}

func apiReferenceRows() []core.Row {
	return []core.Row{
		sectionTitle("API Reference", "Code snippets are isolated here so the showcase pages stay focused on rendered output."),
		row.New(20).Add(
			col.New(4).Add(text.New("Create from HTML", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: blue})),
			col.New(4).Add(text.New("Compose with rows", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: teal})),
			col.New(4).Add(text.New("Add tables", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: amber})),
		),
		codeBlock(`doc, err := paper.FromHTML("<h1>Hello</h1><p>World</p>")
_ = doc.Save("out.pdf")`),
		spacer(4),
		codeBlock(`m.AddRows(
    row.New().Add(col.New(7).Add(main), col.New(5).Add(side)),
    row.New(18).Add(text.NewCol(12, "Fixed-height band")),
)`),
		spacer(4),
		codeBlock(`tbl, err := table.New(cells,
    table.WithColumnWidths([]float64{2, 1, 1}),
)
m.AddRows(row.New().Add(col.New(12).Add(tbl)))`),
		spacer(5),
		thinRule(),
		spacer(5),
		row.New(19).Add(
			col.New(4).Add(text.New("Configure grid", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: blue})),
			col.New(4).Add(text.New("Embed HTML", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: teal})),
			col.New(4).Add(text.New("Split sections", props.Text{Family: fontfamily.Helvetica, Style: fontstyle.Bold, Size: 9, Color: amber})),
		),
		codeBlock(`cfg := config.NewBuilder().
    WithMaxGridSize(12).
    WithLeftMargin(15).
    Build()`),
		spacer(4),
		codeBlock(`block, err := htmlcomponent.New("<p>Inside a column</p>")
m.AddAutoRow(col.New(6).Add(block))`),
		spacer(4),
		codeBlock(`m.AddRows(reportHeader(), snapshotTable(), checklist())
m.AddRows(pageBreak())
m.AddRows(appendixRows()...)`),
	}
}

func htmlSupportTable() core.Component {
	t, err := table.New([][]table.Cell{
		{
			{Content: tableText("Input", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Rendered as", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Notes", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Headings, paragraphs, inline tags", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Text and rich text runs", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Supports bold, emphasis, links, colors, and spacing.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("display:flex", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Rows and columns", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("Flex widths quantize to the configured grid size.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("table, border, background", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Table cells and cell styles", false, ink), Style: tableCellStyle(softBlue)},
			{Content: tableText("Useful for reports, invoices, and rich document fragments.", false, ink), Style: tableCellStyle(softBlue)},
		},
	}, table.WithColumnWidths([]float64{1.35, 1.25, 2.2}))
	if err != nil {
		panic(err)
	}
	return t
}

type gridCellSpec struct {
	size  int
	label string
	color *props.Color
}

func gridExampleRow(label string, cells []gridCellSpec) core.Row {
	return row.New(12).Add(
		col.New(3).Add(text.New(label, props.Text{
			Family: fontfamily.Courier,
			Size:   6.5,
			Top:    2,
			Color:  muted,
		})),
		col.New(9).Add(rowStrip(cells)),
	)
}

func rowStrip(cells []gridCellSpec) core.Component {
	t, err := table.New(gridCells(cells))
	if err != nil {
		panic(err)
	}
	return t
}

func gridCells(cells []gridCellSpec) [][]table.Cell {
	out := make([]table.Cell, 0, len(cells))
	for _, cell := range cells {
		out = append(out, table.Cell{
			Content: text.New(cell.label, props.Text{
				Family: fontfamily.Helvetica,
				Style:  fontstyle.Bold,
				Size:   8,
				Align:  align.Center,
				Color:  white,
			}),
			Colspan: cell.size,
			Style: &props.Cell{
				BackgroundColor: cell.color,
				BorderType:      border.Full,
				BorderColor:     white,
				BorderThickness: 0.35,
				PaddingTop:      2.2,
				PaddingBottom:   2.2,
			},
		})
	}
	return [][]table.Cell{out}
}

func sampleTable() (*table.Table, error) {
	return table.New([][]table.Cell{
		{
			{Content: tableText("Capability", true, white), Style: tableHeaderStyle()},
			{Content: tableText("API", true, white), Style: tableHeaderStyle()},
			{Content: tableText("Use when", true, white), Style: tableHeaderStyle()},
		},
		{
			{Content: tableText("Grid", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("row.New + col.New", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("You need deterministic, programmatic layout.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("HTML", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("paper.FromHTML / AddHTML", false, ink), Style: tableCellStyle(nil)},
			{Content: tableText("The source is already HTML or CSS-styled content.", false, ink), Style: tableCellStyle(nil)},
		},
		{
			{Content: tableText("Metrics", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("paper.NewMetricsDecorator", false, ink), Style: tableCellStyle(softGold)},
			{Content: tableText("You want generation timings and output size reports.", false, ink), Style: tableCellStyle(softGold)},
		},
	}, table.WithColumnWidths([]float64{1.1, 1.25, 2.3}))
}

func tableHeaderStyle() *props.Cell {
	return &props.Cell{
		BackgroundColor: deepInk,
		BorderType:      border.Full,
		BorderColor:     deepInk,
		PaddingTop:      2,
		PaddingLeft:     2,
		PaddingBottom:   2,
	}
}

func tableCellStyle(background *props.Color) *props.Cell {
	return &props.Cell{
		BackgroundColor: background,
		BorderType:      border.Full,
		BorderColor:     lineSoftC,
		BorderThickness: 0.25,
		PaddingTop:      1.8,
		PaddingLeft:     2,
		PaddingBottom:   1.8,
	}
}

func tableText(value string, bold bool, color *props.Color) core.Component {
	style := fontstyle.Normal
	if bold {
		style = fontstyle.Bold
	}
	return text.New(value, props.Text{
		Family: fontfamily.Helvetica,
		Style:  style,
		Size:   7.5,
		Color:  color,
	})
}

func cardTitle(title string, color *props.Color) core.Component {
	return text.New(title, props.Text{
		Family: serifFont,
		Style:  fontstyle.Bold,
		Size:   10,
		Top:    3,
		Left:   4,
		Color:  color,
	})
}

func metricCol(size int, value, label string, bg, accent *props.Color) core.Col {
	return col.New(size).Add(
		text.New(value, props.Text{
			Family: fontfamily.Helvetica,
			Style:  fontstyle.Bold,
			Size:   11,
			Top:    3,
			Align:  align.Center,
			Color:  accent,
		}),
		text.New(label, props.Text{
			Family: fontfamily.Helvetica,
			Size:   7,
			Top:    10,
			Left:   3,
			Right:  3,
			Align:  align.Center,
			Color:  ink,
		}),
	).WithStyle(cardStyle(bg, accent))
}

func cardCol(size int, title, body string, bg, accent *props.Color) core.Col {
	return col.New(size).Add(
		cardTitle(title, accent),
		text.New(body, props.Text{
			Family:          fontfamily.Helvetica,
			Size:            8,
			Top:             11,
			Left:            4,
			Right:           4,
			VerticalPadding: 1.2,
			Color:           ink,
		}),
	).WithStyle(cardStyle(bg, borderC))
}

func sectionTitle(title, subtitle string) core.Row {
	return row.New(17).Add(col.New(12).Add(
		text.New(title, props.Text{
			Family: serifFont,
			Style:  fontstyle.Bold,
			Size:   16,
			Top:    1,
			Color:  brand,
		}),
		text.New(subtitle, props.Text{
			Family: fontfamily.Helvetica,
			Size:   8.5,
			Top:    10,
			Color:  muted,
		}),
	))
}

func codeBlock(code string) core.Row {
	lines := strings.Split(strings.Trim(code, "\n"), "\n")
	height := 7 + float64(len(lines))*3.2
	return row.New(height).Add(col.New(12).Add(codeTextComponents(code)...)).WithStyle(&props.Cell{
		BackgroundColor: rgb(247, 247, 247),
		BorderType:      border.Full,
		BorderColor:     borderC,
		BorderThickness: 0.25,
	})
}

func thinRule() core.Row {
	return row.New(1.2).Add(col.New(12).Add(line.New(props.Line{
		Color:     borderC,
		Thickness: 0.25,
	})))
}

func infoCol(size int, title, body string, accent *props.Color) core.Col {
	return col.New(size).Add(
		text.New(title, props.Text{
			Family: fontfamily.Helvetica,
			Style:  fontstyle.Bold,
			Size:   9,
			Top:    3,
			Color:  accent,
		}),
		text.New(body, props.Text{
			Family:          fontfamily.Helvetica,
			Size:            8,
			Top:             12,
			Right:           5,
			VerticalPadding: 1.1,
			Color:           ink,
		}),
	)
}

func codeTextComponents(code string) []core.Component {
	lines := strings.Split(strings.Trim(code, "\n"), "\n")
	components := make([]core.Component, 0, len(lines))
	for i, line := range lines {
		components = append(components, text.New(line, props.Text{
			Family: fontfamily.Courier,
			Size:   7,
			Top:    3 + float64(i)*3.2,
			Left:   4,
			Right:  4,
			Color:  ink,
		}))
	}
	return components
}

func cardStyle(bg, stroke *props.Color) *props.Cell {
	return &props.Cell{
		BackgroundColor: bg,
		BorderType:      border.Full,
		BorderColor:     stroke,
		BorderThickness: 0.25,
		BorderRadius:    2,
		MarginLeft:      0.9,
		MarginRight:     0.9,
	}
}

func spacer(height float64) core.Row {
	return row.New(height).Add(col.New(12))
}

func pageBreak() core.Row {
	return translate.NewPageBreakRow()
}

func rgb(r, g, b int) *props.Color {
	return &props.Color{Red: r, Green: g, Blue: b}
}

func rgba(r, g, b int, a float64) *props.Color {
	return &props.Color{Red: r, Green: g, Blue: b, Alpha: &a}
}
