// html-demo generates a polished invoice PDF that combines Maroto's native
// header/footer/page-number support with an HTML body parsed via pkg/html.
package main

import (
	"fmt"
	"log"
	"os"

	maroto "github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/col"
	"github.com/johnfercher/maroto/v2/pkg/components/line"
	"github.com/johnfercher/maroto/v2/pkg/components/row"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontfamily"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"
)

const body = `
<html>
<head>
  <style>
    h1 { color: #1a3e72; font-size: 22pt }
    h2 { color: #1a3e72; font-size: 14pt }
    h3 { color: #1a3e72; font-size: 11pt }
    .muted   { color: #6a6a6a }
    .accent  { color: #c0392b }
    .small   { font-size: 9pt }
    .parties { display: flex; gap: 6mm }
    .meta    { display: flex; flex-direction: column; row-gap: 1mm }
    .totals  { display: flex; justify-content: space-between }
    .totals-left  { /* default flex behavior, takes proportional space */ }
  </style>
</head>
<body>
  <h1>Invoice #2026-0042</h1>
  <p class="muted">Issued 19 May 2026 — Payment due within 30 days</p>

  <div class="parties">
    <div>
      <h3>Bill to</h3>
      <p><b>Acme Corporation</b><br>
      123 Industrial Way<br>
      Springfield, IL 62701<br>
      <span class="muted">accounts@acme.example</span></p>
    </div>
    <div>
      <h3>Ship to</h3>
      <p><b>Acme Warehouse #4</b><br>
      890 Logistics Blvd<br>
      Springfield, IL 62702<br>
      <span class="muted">receiving@acme.example</span></p>
    </div>
    <div>
      <h3>Payment</h3>
      <p>Net 30 days<br>
      <b>First National Bank</b><br>
      Account 0123-4567<br>
      <span class="muted">SWIFT FNBKUS33</span></p>
    </div>
  </div>

  <h2>Summary</h2>
  <p>Thank you for your <i>continued</i> business this quarter. Below is the itemised
  breakdown of services and goods provided.</p>

  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Widget Pro (premium edition)</td><td>3</td><td>$10.00</td><td>$30.00</td></tr>
      <tr><td>Gadget Plus (extended warranty)</td><td>2</td><td>$25.00</td><td>$50.00</td></tr>
      <tr><td>Onboarding services</td><td>4 hours</td><td>$75.00</td><td>$300.00</td></tr>
      <tr><td>Travel reimbursement</td><td>1</td><td>$120.00</td><td>$120.00</td></tr>
      <tr><td colspan="3"><b>Subtotal</b></td><td><b>$500.00</b></td></tr>
      <tr><td colspan="3">Tax (8%)</td><td>$40.00</td></tr>
      <tr><td colspan="3"><b>Amount due</b></td><td><b class="accent">$540.00</b></td></tr>
    </tbody>
  </table>

  <div class="totals">
    <div style="flex:0 0 50%"><b>Amount due (final)</b></div>
    <div style="flex:0 0 25%" class="accent"><b>$540.00 USD</b></div>
  </div>

  <h2>Payment instructions</h2>
  <ol>
    <li>Wire transfer to <b>Account 0123-4567</b> at First National Bank</li>
    <li>Reference your invoice number <b>#2026-0042</b> in the memo</li>
    <li>Confirm via email to <a href="mailto:billing@maroto.example">billing@maroto.example</a></li>
  </ol>

  <h2>Notes</h2>
  <ul>
    <li>All prices are quoted in USD</li>
    <li>Late payments incur a <b>1.5% monthly</b> service charge</li>
    <li>For questions, reach out to <a href="https://example.com/support">our support team</a></li>
  </ul>

  <hr>
  <p class="small muted">This invoice was generated by Maroto's pure-Go HTML to PDF pipeline.
  No browser, no Node, no external binaries — just Go.</p>
</body>
</html>`

func main() {
	cfg := config.NewBuilder().
		WithPageNumber(props.PageNumber{
			Pattern: "Page {current} of {total}",
			Place:   props.RightBottom,
			Family:  fontfamily.Helvetica,
			Size:    9,
			Color:   &props.Color{Red: 120, Green: 120, Blue: 120},
		}).
		WithLeftMargin(20).
		WithTopMargin(15).
		WithRightMargin(20).
		WithBottomMargin(15).
		Build()

	m := maroto.New(cfg)

	if err := m.RegisterHeader(buildHeader()...); err != nil {
		log.Fatalf("register header: %v", err)
	}
	if err := m.RegisterFooter(buildFooter()...); err != nil {
		log.Fatalf("register footer: %v", err)
	}

	if err := m.AddHTML(body); err != nil {
		log.Fatalf("add html: %v", err)
	}

	doc, err := m.Generate()
	if err != nil {
		log.Fatalf("generate: %v", err)
	}

	out := "/Users/avdo/maroto/test/output/html-demo.pdf"
	if err := doc.Save(out); err != nil {
		log.Fatalf("save: %v", err)
	}
	info, _ := os.Stat(out)
	fmt.Printf("Wrote %s (%d bytes)\n", out, info.Size())
}

// buildHeader returns the rows that render on every page above the body.
func buildHeader() []core.Row {
	dark := &props.Color{Red: 26, Green: 62, Blue: 114}
	muted := &props.Color{Red: 120, Green: 120, Blue: 120}

	titleRow := row.New(10).Add(
		col.New(8).Add(text.New("MAROTO INVOICE SYSTEM", props.Text{
			Family: fontfamily.Helvetica,
			Style:  fontstyle.Bold,
			Size:   14,
			Color:  dark,
		})),
		col.New(4).Add(text.New("invoices@maroto.example", props.Text{
			Family: fontfamily.Helvetica,
			Size:   9,
			Align:  align.Right,
			Color:  muted,
		})),
	)

	dividerRow := row.New(2).Add(col.New(12).Add(line.New(props.Line{
		Color:     dark,
		Thickness: 0.6,
	})))

	return []core.Row{titleRow, dividerRow}
}

// buildFooter returns the rows that render on every page below the body.
func buildFooter() []core.Row {
	muted := &props.Color{Red: 120, Green: 120, Blue: 120}

	dividerRow := row.New(2).Add(col.New(12).Add(line.New(props.Line{
		Color:     muted,
		Thickness: 0.3,
	})))

	infoRow := row.New(6).Add(
		col.New(8).Add(text.New("Maroto Invoice System — confidential", props.Text{
			Family: fontfamily.Helvetica,
			Size:   8,
			Color:  muted,
		})),
		// the page-number slot is filled by config.WithPageNumber on the right
		col.New(4).Add(text.New("", props.Text{})),
	)

	return []core.Row{dividerRow, infoRow}
}
